import { V, type V3 } from '../utils/math.js';
import { Mesh, LAYOUT, type GL2 } from './gl.js';

/** Accumulates indexed geometry with per-vertex colour, skin weights and material id. */
export class MeshBuilder {
  pos: number[] = [];
  nrm: number[] = [];
  col: number[] = [];
  bone: number[] = [];
  wt: number[] = [];
  mat: number[] = [];
  idx: number[] = [];
  get count() { return this.pos.length / 3; }

  vert(p: V3, c: V3, b0 = 0, b1 = 0, w0 = 1, w1 = 0, m = 0, n: V3 = [0, 1, 0]): number {
    this.pos.push(p[0], p[1], p[2]);
    this.nrm.push(n[0], n[1], n[2]);
    this.col.push(c[0], c[1], c[2]);
    this.bone.push(b0, b1);
    this.wt.push(w0, w1);
    this.mat.push(m);
    return this.count - 1;
  }
  tri(a: number, b: number, c: number) { this.idx.push(a, b, c); }
  quad(a: number, b: number, c: number, d: number) { this.idx.push(a, b, c, a, c, d); }

  /** smooth vertex normals from the index buffer */
  computeNormals() {
    const n = new Float32Array(this.pos.length);
    for (let i = 0; i < this.idx.length; i += 3) {
      const a = this.idx[i], b = this.idx[i + 1], c = this.idx[i + 2];
      const pa: V3 = [this.pos[a * 3], this.pos[a * 3 + 1], this.pos[a * 3 + 2]];
      const pb: V3 = [this.pos[b * 3], this.pos[b * 3 + 1], this.pos[b * 3 + 2]];
      const pc: V3 = [this.pos[c * 3], this.pos[c * 3 + 1], this.pos[c * 3 + 2]];
      const f = V.cross(V.sub(pb, pa), V.sub(pc, pa));
      for (const v of [a, b, c]) { n[v * 3] += f[0]; n[v * 3 + 1] += f[1]; n[v * 3 + 2] += f[2]; }
    }
    for (let i = 0; i < n.length; i += 3) {
      const l = Math.hypot(n[i], n[i + 1], n[i + 2]) || 1;
      this.nrm[i] = n[i] / l; this.nrm[i + 1] = n[i + 1] / l; this.nrm[i + 2] = n[i + 2] / l;
    }
    return this;
  }

  /** non-indexed flat-shaded triangle */
  flatTri(a: V3, b: V3, c: V3, col: V3, mat = 0) {
    const n = V.norm(V.cross(V.sub(b, a), V.sub(c, a)));
    const i = this.vert(a, col, 0, 0, 1, 0, mat, n);
    this.vert(b, col, 0, 0, 1, 0, mat, n);
    this.vert(c, col, 0, 0, 1, 0, mat, n);
    this.idx.push(i, i + 1, i + 2);
  }
  flatQuad(a: V3, b: V3, c: V3, d: V3, col: V3, mat = 0) { this.flatTri(a, b, c, col, mat); this.flatTri(a, c, d, col, mat); }

  /** append another builder (indices are re-based) */
  append(o: MeshBuilder) {
    const base = this.count;
    this.pos.push(...o.pos); this.nrm.push(...o.nrm); this.col.push(...o.col);
    this.bone.push(...o.bone); this.wt.push(...o.wt); this.mat.push(...o.mat);
    for (const i of o.idx) this.idx.push(i + base);
  }

  buildStatic(): { verts: Float32Array; indices: Uint16Array | Uint32Array } {
    const n = this.count, s = LAYOUT.static.stride, v = new Float32Array(n * s);
    for (let i = 0; i < n; i++) {
      v.set(this.pos.slice(i * 3, i * 3 + 3), i * s);
      v.set(this.nrm.slice(i * 3, i * 3 + 3), i * s + 3);
      v.set(this.col.slice(i * 3, i * 3 + 3), i * s + 6);
    }
    return { verts: v, indices: n > 65535 ? new Uint32Array(this.idx) : new Uint16Array(this.idx) };
  }
  buildSkinned(): { verts: Float32Array; indices: Uint16Array | Uint32Array } {
    const n = this.count, s = LAYOUT.skinned.stride, v = new Float32Array(n * s);
    for (let i = 0; i < n; i++) {
      const o = i * s;
      v[o] = this.pos[i * 3]; v[o + 1] = this.pos[i * 3 + 1]; v[o + 2] = this.pos[i * 3 + 2];
      v[o + 3] = this.nrm[i * 3]; v[o + 4] = this.nrm[i * 3 + 1]; v[o + 5] = this.nrm[i * 3 + 2];
      v[o + 6] = this.col[i * 3]; v[o + 7] = this.col[i * 3 + 1]; v[o + 8] = this.col[i * 3 + 2];
      v[o + 9] = this.bone[i * 2]; v[o + 10] = this.bone[i * 2 + 1];
      v[o + 11] = this.wt[i * 2]; v[o + 12] = this.wt[i * 2 + 1];
      v[o + 13] = this.mat[i];
    }
    return { verts: v, indices: n > 65535 ? new Uint32Array(this.idx) : new Uint16Array(this.idx) };
  }
  toStaticMesh(gl: GL2) { const b = this.buildStatic(); return new Mesh(gl, LAYOUT.static, b.verts, b.indices); }
  toSkinnedMesh(gl: GL2) { const b = this.buildSkinned(); return new Mesh(gl, LAYOUT.skinned, b.verts, b.indices); }

  /** Wavefront OBJ text (positions, normals, vertex colours as comments) for the bind pose mesh */
  toOBJ(name: string): string {
    const out: string[] = [`# ${name} - generated by Anime Fight Engine`, `o ${name}`];
    for (let i = 0; i < this.count; i++) out.push(`v ${this.pos[i * 3].toFixed(5)} ${this.pos[i * 3 + 1].toFixed(5)} ${this.pos[i * 3 + 2].toFixed(5)} ${this.col[i * 3].toFixed(3)} ${this.col[i * 3 + 1].toFixed(3)} ${this.col[i * 3 + 2].toFixed(3)}`);
    for (let i = 0; i < this.count; i++) out.push(`vn ${this.nrm[i * 3].toFixed(4)} ${this.nrm[i * 3 + 1].toFixed(4)} ${this.nrm[i * 3 + 2].toFixed(4)}`);
    for (let i = 0; i < this.idx.length; i += 3) {
      const a = this.idx[i] + 1, b = this.idx[i + 1] + 1, c = this.idx[i + 2] + 1;
      out.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
    }
    return out.join('\n');
  }
}

/** an orthonormal (u,v) pair perpendicular to `dir`, using `hint` as the reference for `v` */
export function perp(dir: V3, hint: V3 = [0, 0, 1]): { u: V3; v: V3 } {
  const d = V.norm(dir);
  let v = V.sub(hint, V.mul(d, V.dot(hint, d)));
  if (V.len(v) < 1e-4) v = V.sub([1, 0, 0], V.mul(d, d[0]));
  v = V.norm(v);
  const u = V.norm(V.cross(v, d));
  return { u, v };
}

export interface Ring {
  c: V3; u: V3; v: V3; // centre and radius-scaled axes
  col?: V3;
  bones?: [number, number]; w?: [number, number];
  mat?: number;
}

/** Skins a chain of rings into a tube. Optionally caps the ends (closed) with a centre fan. */
export function loft(mb: MeshBuilder, rings: Ring[], sides: number, capStart = true, capEnd = true, defCol: V3 = [1, 1, 1], defMat = 0) {
  const base = mb.count;
  for (const r of rings) {
    for (let s = 0; s < sides; s++) {
      const a = (s / sides) * Math.PI * 2, ca = Math.cos(a), sa = Math.sin(a);
      const p: V3 = [r.c[0] + r.u[0] * ca + r.v[0] * sa, r.c[1] + r.u[1] * ca + r.v[1] * sa, r.c[2] + r.u[2] * ca + r.v[2] * sa];
      const b = r.bones ?? [0, 0], w = r.w ?? [1, 0];
      mb.vert(p, r.col ?? defCol, b[0], b[1], w[0], w[1], r.mat ?? defMat);
    }
  }
  for (let i = 0; i < rings.length - 1; i++) {
    for (let s = 0; s < sides; s++) {
      const s1 = (s + 1) % sides;
      const a = base + i * sides + s, b = base + i * sides + s1, c = base + (i + 1) * sides + s1, d = base + (i + 1) * sides + s;
      mb.quad(a, b, c, d);
    }
  }
  const cap = (ri: number, flip: boolean) => {
    const r = rings[ri];
    const b = r.bones ?? [0, 0], w = r.w ?? [1, 0];
    const ci = mb.vert(r.c, r.col ?? defCol, b[0], b[1], w[0], w[1], r.mat ?? defMat);
    for (let s = 0; s < sides; s++) {
      const s1 = (s + 1) % sides;
      const a = base + ri * sides + s, bb = base + ri * sides + s1;
      if (flip) mb.tri(ci, bb, a); else mb.tri(ci, a, bb);
    }
  };
  if (capStart) cap(0, false);
  if (capEnd) cap(rings.length - 1, true);
}

/** ring axes for a tube travelling along `dir` with elliptical radii (rx along `hint`, rz across) */
export function ringAt(c: V3, dir: V3, rx: number, rz: number, hint: V3 = [0, 0, 1]): Ring {
  const { u, v } = perp(dir, hint);
  return { c, u: V.mul(u, rx), v: V.mul(v, rz) };
}

// ----------------------------------------------------------------- primitives (flat shaded, for props)
export function icoPositions(subdiv: number): { verts: V3[]; faces: [number, number, number][] } {
  const t = (1 + Math.sqrt(5)) / 2;
  let verts: V3[] = [[-1, t, 0], [1, t, 0], [-1, -t, 0], [1, -t, 0], [0, -1, t], [0, 1, t], [0, -1, -t], [0, 1, -t], [t, 0, -1], [t, 0, 1], [-t, 0, -1], [-t, 0, 1]].map((v) => V.norm(v as V3));
  let faces: [number, number, number][] = [[0, 11, 5], [0, 5, 1], [0, 1, 7], [0, 7, 10], [0, 10, 11], [1, 5, 9], [5, 11, 4], [11, 10, 2], [10, 7, 6], [7, 1, 8], [3, 9, 4], [3, 4, 2], [3, 2, 6], [3, 6, 8], [3, 8, 9], [4, 9, 5], [2, 4, 11], [6, 2, 10], [8, 6, 7], [9, 8, 1]];
  for (let s = 0; s < subdiv; s++) {
    const cache = new Map<string, number>();
    const mid = (a: number, b: number) => {
      const k = a < b ? `${a}_${b}` : `${b}_${a}`;
      let i = cache.get(k);
      if (i === undefined) { verts.push(V.norm(V.mul(V.add(verts[a], verts[b]), 0.5))); i = verts.length - 1; cache.set(k, i); }
      return i;
    };
    const nf: [number, number, number][] = [];
    for (const [a, b, c] of faces) {
      const ab = mid(a, b), bc = mid(b, c), ca = mid(c, a);
      nf.push([a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca]);
    }
    faces = nf;
  }
  return { verts, faces };
}

/** UV sphere as a flat MeshBuilder-compatible static mesh (smooth normals) */
export function uvSphere(seg: number, rings: number, col: V3 = [1, 1, 1]): MeshBuilder {
  const mb = new MeshBuilder();
  for (let y = 0; y <= rings; y++) {
    const v = y / rings, th = v * Math.PI;
    for (let x = 0; x <= seg; x++) {
      const u = x / seg, ph = u * Math.PI * 2;
      const p: V3 = [Math.sin(th) * Math.cos(ph), Math.cos(th), Math.sin(th) * Math.sin(ph)];
      mb.vert(p, col, 0, 0, 1, 0, 0, p);
    }
  }
  for (let y = 0; y < rings; y++) for (let x = 0; x < seg; x++) {
    const a = y * (seg + 1) + x, b = a + 1, c = a + seg + 1, d = c + 1;
    mb.tri(a, c, b); mb.tri(b, c, d);
  }
  return mb;
}

/** flat unit disc in the XZ plane (fan), used by shockwave rings */
export function discMesh(seg = 96): MeshBuilder {
  const mb = new MeshBuilder();
  const c = mb.vert([0, 0, 0], [1, 1, 1], 0, 0, 1, 0, 0, [0, 1, 0]);
  for (let i = 0; i <= seg; i++) {
    const a = (i / seg) * Math.PI * 2;
    mb.vert([Math.cos(a), 0, Math.sin(a)], [1, 1, 1], 0, 0, 1, 0, 0, [0, 1, 0]);
  }
  for (let i = 0; i < seg; i++) mb.tri(c, c + 1 + i + 1, c + 1 + i);
  return mb;
}

export function hex(c: string): V3 {
  const n = parseInt(c.replace('#', ''), 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}
